### ISSUE TITLE
Django 5: log cancellation of async view

### ISSUE THREAD

**Issue by jrobichaud** [jrobichaud/django-structlog#351]
Django 5.0 now handles cancelling of `async` request:

```python
async def my_view(request):
    try:
        # Do some work
        ...
    except asyncio.CancelledError:
        # Handle disconnect
        raise
```
See:
- [handling-disconnects](https://docs.djangoproject.com/en/dev/topics/async/#handling-disconnects)
- [request-response-streaming-disconnect](https://docs.djangoproject.com/en/dev/ref/request-response/#request-response-streaming-disconnect)

Todo:
- [X]  Refactor demo project to use js fetch instead of dummy iframe (fixed by #353 )
- [X]  (optional) Add front-end log to see request results (fixed by #353 )
- [x]  Add to demo project:
    - [X]  implement async streaming view (currently most middlewares crashes in the project)
    - [x] cancel of the async view (currently asgi hang)
    - [X]  cancel of the async streaming view (fixed by #353)
- [x] (if necessary) fix django-structlog for these four examples (done for streaming view #353 )
- [X] (if possible) log if the request disconnected (fixed by #353 for streaming views)

- [X] Example of cancelling an async call in js (to be added in `django_structlog_demo_project/static/js/project.js`):

```javascript
function callAsync() {
    const abortController = new AbortController();
    fetch( "/async_view",  {
        method: 'get',
        signal: abortController.signal,
    })
    .then(function(response) {
        console.log("Async request completed");
    }).catch(function(error) {
        console.error(`Error: ${error}`);
    });
    setTimeout(()=>abortController.abort(), 10 )
}
```

**Comment by jrobichaud** [comment]
I managed implement streaming view support for both async and sync streaming responses  in #353 

However cancelling async views just freeze the asgi server.

I still don't know if I am doing something wrong or there is a bug in django.

Help would be appreciated.

**Comment by mohamedTbarka** [comment]
@jrobichaud, can u please give more detail about the freezing of the ASGI server ?

**Comment by jrobichaud** [comment]
@mohamedTbarka 

With an async view when cancelling a request with the client, the request does not end in django. Ex: the `request_finished` is never called.

Also, the asgi server is not taking any more requests. I have to restart it.

**Comment by mohamedTbarka** [comment]
@jrobichaud, thanks for ur feedback & colossal efforts regardin' this almighty package, I'll do my best to debug this issue guessin' it's a Django's bug !

**Comment by mohamedTbarka** [comment]
@jrobichaud, thanks for ur feedback & colossal efforts regardin' this almighty package, I'll do my best to debug this issue guessin' it's a Django's bug !

**Comment by jrobichaud** [comment]
@mohamedTbarka thanks!, this is appreciated!

First of all make sure you can reproduce the bug

1. [First start the demo project](https://django-structlog.readthedocs.io/en/latest/demo.html)
2. Open the url
3. Select the `asgi` tab
4. Press the Async View button then press on the Cancel button within 1 second. It should reproduce the bug.

**Comment by mohamedTbarka** [comment]
@jrobichaud 
I've reproduced the bug; debuggin' it, it' a Django's bug apparently !

**Comment by mohamedTbarka** [comment]
@jrobichaud, I'll open a ticket on "Django issues" if u confirm it of course !

**Comment by jrobichaud** [comment]
You are welcome to open a django ticket if you could spot the bug. 

When you do, please add the link here please.

In order to make it easier for django to reproduce it, did you create a clean project from scratch to reproduce the bug? Referencing django-structlog may just cause confusion. What do you think?

**Comment by jrobichaud** [comment]
@mohamedTbarka did you submit django a ticket? 

Django 5 release candidate is next week.

https://code.djangoproject.com/wiki/Version5.0Roadmap

**Comment by jrobichaud** [comment]
The bug is with django-allauth:

https://github.com/pennersr/django-allauth/issues/3566

**Comment by mohamedTbarka** [comment]
@jrobichaud sorry for the delay due to some health issues, thanks for your precious feedback :pray:

**Comment by jrobichaud** [comment]
I am looking for the update of 0.60.0 of django-allauth.

**Comment by mohamedTbarka** [comment]
can u please explain in detail how django-allauth is the origin of the bug ?

**Comment by jrobichaud** [comment]
@mohamedTbarka https://github.com/pennersr/django-allauth/issues/3566 their middleware is not compatible with async requests.
